docker exec -i -t awx_task "yum install krb5-workstation"
docker exec -i -t awx_task "yum install krb5-devel"
docker exec -i -t awx_task "yum install krb5-libs"
docker exec -i -t awx_task "yum install gcc"
docker exec -i -t awx_task "yum install python-devel"
docker exec -i -t awx_task "pip install kerberos"