docker exec -i -t awx_task "sudo apt-get -y install krb5-workstation"
docker exec -i -t awx_task "sudo apt-get -y install krb5-devel"
docker exec -i -t awx_task "sudo apt-get -y install krb5-libs"
docker exec -i -t awx_task "sudo apt-get -y install gcc"
docker exec -i -t awx_task "sudo apt-get -y install python-devel"
docker exec -i -t awx_task "sudo pip install kerberos"